name: generate animation

on:
  # executa automaticamente todo dia a meia-noite
  schedule:
    - cron: "0 0 */1 * *"
  
  # permite executar manualmente a qualquer hora
  workflow_dispatch:
  
  # executa em push para branch master
  push:
    branches:
      - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          svg_out_path_dark: dist/github-contribution-grid-snake-dark.svg
          palette_dark: github-dark
          
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
